In [3]:
import csv
import numpy as np 
import sklearn
import pandas as pd
from sklearn.gaussian_process.kernels import RBF
from sklearn.model_selection import train_test_split
tf=pd.read_csv('train_new_feature.csv', sep=',',header=0)
tl = pd.read_csv('train_labels.csv',sep=',',header=0)
tf = tf.astype(float)
tl = tl.astype(float)
tl = tl.sort_values(['pid'])
tl_np = np.asarray(tl)
tl_np = tl_np.reshape(tl_np.shape[0],-1)
tf2 = tf.groupby(['pid'])
tf3= []
for p in tf2:
    tf3.append(np.asarray(p[1].values).reshape(-1,))
tf_np = np.asarray(tf3)
x_train, x_test, y_train, y_test = train_test_split(tf_np, tl_np[:,1], test_size = 0.3)
#tf=pd.read_csv('train_features.csv', sep=',',header=0)#skiprows = 1)
#tf = pd.read_csv('test_features.csv',sep=',',header=0)#skiprows = 1)

In [1]:
import csv
import numpy as np 
import sklearn
import pandas as pd
from sklearn.gaussian_process.kernels import RBF
from sklearn.model_selection import train_test_split
tf=pd.read_csv('train_new_feature.csv', sep=',',header=0)
tl = pd.read_csv('train_labels.csv',sep=',',header=0)
tf = tf.astype(float)
tl = tl.astype(float)
tl = tl.sort_values(['pid'])
tl_np = np.asarray(tl['LABEL_Heartrate'])
tl_np = tl_np.reshape(tl_np.shape[0],-1)
tf2 = tf.groupby(['pid'])
tf3= []
for p in tf2:
    tf3.append(np.asarray(p[1]['Heartrate']).reshape(-1,))
tf_np = np.asarray(tf3)
x_train, x_test, y_train, y_test = train_test_split(tf_np, tl_np, test_size = 0.3)

In [5]:
from sklearn import svm
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
x_train, x_test, y_train, y_test = train_test_split(tf_np[:,-2:], tl_np.reshape(-1,), test_size = 0.3)
clf = svm.SVR(gamma='scale')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print (np.mean((y_pred-y_test)**2))

77.25740587887582


In [8]:
tf1 = pd.read_csv('train_features.csv', sep=',',header=0)#skiprows = 1)
#tf = pd.read_csv('test_features.csv',sep=',',header=0)#skiprows = 1)

In [10]:
tf1 = tf1.sort_values(['pid',['Time']])
tf2 = tf1.groupby(['pid'])

0         94.0
1         99.0
2         92.0
3         88.0
4         81.0
          ... 
227935    80.0
227936    83.0
227937    80.0
227938    75.0
227939    79.0
Name: Heartrate, Length: 227940, dtype: float64

In [4]:
import numpy as np 
a = np.zeros((1,10))
b=np.ones((2,10))
print(np.concatenate((a,b),axis=0))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
